--sql query for fnol phase 1.3
CREATE TABLE [dbo].[Claims](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AreYouSatisfied_correctPerson] [nvarchar](255) NULL,
	[Cause] [nvarchar](255) NULL,
	[ClaimHandler] [nvarchar](255) NULL,
	[ConditionRoad] [nvarchar](255) NULL,
	[CustomerMailID] [nvarchar](255) NULL,
	[CoverageType] [nvarchar](255) NULL,
	[DeathInjuryAddress_1] [nvarchar](255) NULL,
	[DeathInjuryAge_1] [nvarchar](255) NULL,
	[DeathInjuryName_1] [nvarchar](255) NULL,
	[DeathInjuryNature_1] [nvarchar](255) NULL,
	[DeathInjuryRemovedHospital_1] [nvarchar](255) NULL,
	[DeathInjuryAddress_2] [nvarchar](255) NULL,
	[DeathInjuryAge_2] [nvarchar](255) NULL,
	[DeathInjuryName_2] [nvarchar](255) NULL,
	[DeathInjuryNature_2] [nvarchar](255) NULL,
	[DeathInjuryRemovedHospital_2] [nvarchar](255) NULL,
	[DeathInjuryAddress_3] [nvarchar](255) NULL,
	[DeathInjuryAge_3] [nvarchar](255) NULL,
	[DeathInjuryName_3] [nvarchar](255) NULL,
	[DeathInjuryNature_3] [nvarchar](255) NULL,
	[DeathInjuryRemovedHospital_3] [nvarchar](255) NULL,
	[DeathInjuryAddress_4] [nvarchar](255) NULL,
	[DeathInjuryAge_4] [nvarchar](255) NULL,
	[DeathInjuryName_4] [nvarchar](255) NULL,
	[DeathInjuryNature_4] [nvarchar](255) NULL,
	[DeathInjuryRemovedHospital_4] [nvarchar](255) NULL,
	[DeathInjuryAddress_5] [nvarchar](255) NULL,
	[DeathInjuryAge_5] [nvarchar](255) NULL,
	[DeathInjuryName_5] [nvarchar](255) NULL,
	[DeathInjuryNature_5] [nvarchar](255) NULL,
	[DeathInjuryRemovedHospital_5] [nvarchar](255) NULL,
	[DescofOccurence] [nvarchar](3000) NULL,
	[DetailsofI_D] [nvarchar](3000) NULL,
	[DidConstableIssueWarn] [nvarchar](255) NULL,
	[DidConstIssWarntoWhom] [nvarchar](255) NULL,
	[Didyoucountpassengers] [nvarchar](255) NULL,
	[DidPoliceTakeParticulars] [nvarchar](255) NULL,
	[Dothepartiesknoweachother] [nvarchar](255) NULL,
	[Doesthedamagedrvorpassengerinj] [nvarchar](255) NULL,
	[DriverAddress] [nvarchar](255) NULL,
	[DriverDOB] [nvarchar](255) NULL,
	[DriverName] [nvarchar](255) NULL,
	[DriverPhone] [nvarchar](255) NULL,
	[EffectiveDate] [nvarchar](255) NULL,
	[ExpirationDate] [nvarchar](255) NULL,
	[Haveyouattendedprevinvolvsamevehdrv] [nvarchar](255) NULL,
	[Haveyouseenothracc] [nvarchar](255) NULL,
	[Haveyoutakenphoto] [nvarchar](255) NULL,
	[InsuredName] [nvarchar](255) NULL,
	[InvolvedParties] [nvarchar](255) NULL,
	[IsthedriverAgstPol] [nvarchar](255) NULL,
	[Isthedriveruncooperative] [nvarchar](255) NULL,
	[IsthenatureofInjconsis] [nvarchar](255) NULL,
	[IsthesamePoliceOfficer] [nvarchar](255) NULL,
	[Isthevehdamageconsis] [nvarchar](255) NULL,
	[LicenceExpiry] [nvarchar](255) NULL,
	[License] [nvarchar](255) NULL,
	[Location] [nvarchar](3000) NULL,
	[Namesandphnnumincar] [nvarchar](255) NULL,
	[ParticularsofDamage] [nvarchar](3000) NULL,
	[PoliceName] [nvarchar](255) NULL,
	[PoliceNumber] [nvarchar](255) NULL,
	[PolicyNumber] [nvarchar](255) NULL,
	[Seehowpassbehave] [nvarchar](255) NULL,
	[ThirdPartyDescriptionofDamage_1] [nvarchar](255) NULL,
	[ThirdPartyAddress_1] [nvarchar](255) NULL,
	[ThirdPartyDriverAddress_1] [nvarchar](255) NULL,
	[ThirdPartyDriverName_1] [nvarchar](255) NULL,
	[ThirdPartyDriverTelephone_1] [nvarchar](255) NULL,
	[ThirdPartyInsurance_1] [nvarchar](255) NULL,
	[ThirdPartyMakeModel_1] [nvarchar](255) NULL,
	[ThirdPartyNameofOwner_1] [nvarchar](255) NULL,
	[ThirdPartyRegistrationNumber_1] [nvarchar](255) NULL,
	[ThirdPartyTelephone_1] [nvarchar](255) NULL,
	[TimeofOccurence] [nvarchar](255) NULL,
	[ThirdPartyDescriptionofDamage_2] [nvarchar](255) NULL,
	[ThirdPartyAddress_2] [nvarchar](255) NULL,
	[ThirdPartyDriverAddress_2] [nvarchar](255) NULL,
	[ThirdPartyDriverName_2] [nvarchar](255) NULL,
	[ThirdPartyDriverTelephone_2] [nvarchar](255) NULL,
	[ThirdPartyInsurance_2] [nvarchar](255) NULL,
	[ThirdPartyMakeModel_2] [nvarchar](255) NULL,
	[ThirdPartyNameofOwner_2] [nvarchar](255) NULL,
	[ThirdPartyRegistrationNumber_2] [nvarchar](255) NULL,
	[ThirdPartyTelephone_2] [nvarchar](255) NULL,
	[ThirdPartyDescriptionofDamage_3] [nvarchar](255) NULL,
	[ThirdPartyAddress_3] [nvarchar](255) NULL,
	[ThirdPartyDriverAddress_3] [nvarchar](255) NULL,
	[ThirdPartyDriverName_3] [nvarchar](255) NULL,
	[ThirdPartyDriverTelephone_3] [nvarchar](255) NULL,
	[ThirdPartyInsurance_3] [nvarchar](255) NULL,
	[ThirdPartyMakeModel_3] [nvarchar](255) NULL,
	[ThirdPartyNameofOwner_3] [nvarchar](255) NULL,
	[ThirdPartyRegistrationNumber_3] [nvarchar](255) NULL,
	[ThirdPartyTelephone_3] [nvarchar](255) NULL,
	[ThirdPartyDescriptionofDamage_4] [nvarchar](255) NULL,
	[ThirdPartyAddress_4] [nvarchar](255) NULL,
	[ThirdPartyDriverAddress_4] [nvarchar](255) NULL,
	[ThirdPartyDriverName_4] [nvarchar](255) NULL,
	[ThirdPartyDriverTelephone_4] [nvarchar](255) NULL,
	[ThirdPartyInsurance_4] [nvarchar](255) NULL,
	[ThirdPartyMakeModel_4] [nvarchar](255) NULL,
	[ThirdPartyNameofOwner_4] [nvarchar](255) NULL,
	[ThirdPartyRegistrationNumber_4] [nvarchar](255) NULL,
	[ThirdPartyTelephone_4] [nvarchar](255) NULL,
	[ThirdPartyDescriptionofDamage_5] [nvarchar](255) NULL,
	[ThirdPartyAddress_5] [nvarchar](255) NULL,
	[ThirdPartyDriverAddress_5] [nvarchar](255) NULL,
	[ThirdPartyDriverName_5] [nvarchar](255) NULL,
	[ThirdPartyDriverTelephone_5] [nvarchar](255) NULL,
	[ThirdPartyInsurance_5] [nvarchar](255) NULL,
	[ThirdPartyMakeModel_5] [nvarchar](255) NULL,
	[ThirdPartyNameofOwner_5] [nvarchar](255) NULL,
	[ThirdPartyRegistrationNumber_5] [nvarchar](255) NULL,
	[ThirdPartyTelephone_5] [nvarchar](255) NULL,
	[Towing] [nvarchar](255) NULL,
	[TravellingSpeed] [nvarchar](255) NULL,
	[VehicleMakeModel] [nvarchar](255) NULL,
	[VehicleRegistration] [nvarchar](255) NULL,
	[VehicleYear] [nvarchar](255) NULL,
	[WasPoliceInformed] [nvarchar](255) NULL,
	[WasYourhornsounded] [nvarchar](255) NULL,
	[WasthereI_D] [nvarchar](255) NULL,
	[WereHeadlightsWorking] [nvarchar](255) NULL,
	[WhatLightsShowing] [nvarchar](255) NULL,
	[WhereCanthevehbeinvest] [nvarchar](255) NULL,
	[Whereandwhenattendprvacc] [nvarchar](255) NULL,
	[Whereandwhendrvpassotheraccscene] [nvarchar](255) NULL,
	[WheretherePassWitToAcc] [nvarchar](255) NULL,
	[WhyDriverUncooperative] [nvarchar](255) NULL,
	[WitnessAddress_1] [nvarchar](255) NULL,
	[WitnessName_1] [nvarchar](255) NULL,
	[WitnessTelephone_1] [nvarchar](255) NULL,
	[WitnessAddress_2] [nvarchar](255) NULL,
	[WitnessName_2] [nvarchar](255) NULL,
	[WitnessTelephone_2] [nvarchar](255) NULL,
	[WitnessAddress_3] [nvarchar](255) NULL,
	[WitnessName_3] [nvarchar](255) NULL,
	[WitnessTelephone_3] [nvarchar](255) NULL,
	[WitnessAddress_4] [nvarchar](255) NULL,
	[WitnessName_4] [nvarchar](255) NULL,
	[WitnessTelephone_4] [nvarchar](255) NULL,
	[WitnessAddress_5] [nvarchar](255) NULL,
	[WitnessName_5] [nvarchar](255) NULL,
	[WitnessTelephone_5] [nvarchar](255) NULL,
	[UserId] [nvarchar](255) NULL,
	[CompletionDate] [nvarchar](255) NULL,
	[Completiontime] [nvarchar](255) NULL,
	[Datecreated] [nvarchar](255) NULL,
	[Insured] [nvarchar](255) NULL,
	[Ke_y] [nvarchar](255) NULL,
	[Name] [nvarchar](255) NULL,
	[PhoneNumber] [nvarchar](255) NULL,
	[PolicyNo] [nvarchar](255) NULL,
	[Timecreated] [nvarchar](255) NULL,
	[address] [nvarchar](255) NULL,
	[assistance] [nvarchar](255) NULL,
	[latitude] [nvarchar](255) NULL,
	[longitude] [nvarchar](255) NULL,
	[notes] [nvarchar](255) NULL,
	[pickedupdate] [nvarchar](255) NULL,
	[pickeduptime] [nvarchar](255) NULL,
	[reacheddate] [nvarchar](255) NULL,
	[reachedtime] [nvarchar](255) NULL,
	[type] [nvarchar](255) NULL,
	[claimNum] [nvarchar](255) NULL,
	[RPAStatus] [nvarchar](255) NULL,
	[ReasonForDecline] [nvarchar](255) NULL,
	[ClaimStatus] [nvarchar](255) NULL,
)


CREATE TABLE [dbo].[Customer](
	[Policy_id] [nvarchar](255) NULL,
	[Clientid] [float] NULL,
	[Name] [nvarchar](255) NULL,
	[DOB] [datetime] NULL,
	[Address] [nvarchar](255) NULL,
	[MaritalStatus] [nvarchar](255) NULL,
	[Gender] [nvarchar](255) NULL,
	[OldPolNo] [nvarchar](255) NULL,
	[PK_refer] [nvarchar](255) NOT NULL,
)


CREATE TABLE [dbo].[Driver](
	[Policy_id] [nvarchar](255) NULL,
	[PK_ref] [nvarchar](255) NOT NULL,
	[DriverName] [nvarchar](255) NULL,
	[LicenceNum] [nvarchar](255) NULL,
	[LicenceExpDate] [datetime] NULL,
	[DriverAge] [nvarchar](255) NULL,
	[DriverType] [nvarchar](255) NULL,
)


CREATE TABLE [dbo].[Policy](
	[Policy_id] [nvarchar](255) NULL,
	[Risk_ID] [float] NOT NULL,
	[PolicyStatus] [nvarchar](255) NULL,
	[TransactionType] [nvarchar](255) NULL,
	[AgentNumber] [float] NULL,
	[AgentCode] [nvarchar](255) NULL,
	[AgentName] [nvarchar](255) NULL,
	[CoverStartDate] [datetime] NULL,
	[ExpiryDate] [datetime] NULL,
	[CoverageType] [nvarchar](255) NULL,
	[TotalPremium] [float] NULL,
)


CREATE TABLE [dbo].[Users](
	[User_Id] [int] IDENTITY(1,1) NOT NULL,
	[User_Name] [varchar](255) NOT NULL,
	[Role] [varchar](255) NOT NULL,
	[Email] [varchar](255) NOT NULL,
	[Password] [varchar](255) NOT NULL,
	[PhoneNumber] [varchar](255) NOT NULL,
	[U_id] [varchar](255) NULL,
	[App] [varchar](255) NOT NULL,
	[Level] [int] NOT NULL,
	[Createdby] [varchar](255) NOT NULL,
	[session] [varchar](255) NULL,
	[last5] [varchar](255) NULL,
	[temppass] [bit] NULL,
	[lastupdated] [datetime2](7) NULL,
)


CREATE TABLE [dbo].[Vehicle](
	[Policy_id] [nvarchar](255) NULL,
	[Risk_ID] [nvarchar](255) NULL,
	[Make] [nvarchar](255) NULL,
	[Model] [nvarchar](255) NULL,
	[Year] [nvarchar](255) NULL,
	[Value] [nvarchar](255) NULL,
	[Vehicle_Registration] [nvarchar](255) NULL,
	[PK_veh] [nvarchar](255) NOT NULL,
)
